// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh_NsVPiIIafOEf-5wxRxA2KpQi7SAFRY',
    appId: '1:802890927386:web:6a81313b9fda7bbb0c70a3',
    messagingSenderId: '802890927386',
    projectId: 'dressonrent-7eb6b',
    authDomain: 'dressonrent-7eb6b.firebaseapp.com',
    storageBucket: 'dressonrent-7eb6b.firebasestorage.app',
    measurementId: 'G-PFXGCC2KTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbt7w6QZJhjQdhOB1N18G9u9B4xNJYzOA',
    appId: '1:802890927386:android:e5dcd1cc862ff3620c70a3',
    messagingSenderId: '802890927386',
    projectId: 'dressonrent-7eb6b',
    storageBucket: 'dressonrent-7eb6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-14lrJAYNUR8ruxEw1eq09KYZP_VyWQI',
    appId: '1:802890927386:ios:9ae608eba5a63fb80c70a3',
    messagingSenderId: '802890927386',
    projectId: 'dressonrent-7eb6b',
    storageBucket: 'dressonrent-7eb6b.firebasestorage.app',
    iosBundleId: 'com.example.dor',
  );
}
